### ISSUE TITLE
Please explain proccess how to release republica(Google store)

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/rp15#11]

**Comment by championswimmer** [comment]
Given the event is over and another republica app is already on the store
(not made by us), is this a priority anymore?

**Comment by mananwason** [comment]
I agree we should focus in ots companion

**Comment by mariobehling** [comment]
The goal here is to make an app that works with the redata format and make an app that works. We have give release rights to several people and now Rafal has issues releasing. We do not want to depend on one person for release. So this question is independent of the specific rp app and the issue needs to be cleared.

**Comment by mariobehling** [comment]
@rafalkowalski Please also try to be more specific when you post an issue and explain the details.
@mananwason Rafal explained to me he has issues with the certificate.
Could you please talk to each other?

**Comment by mananwason** [comment]
@rafalkowalski What issue are you getting?

**Comment by rafalkowalski** [comment]
" Upload failed

You uploaded an APK that is signed with a different certificate to your previous APKs. You must use the same certificate."

**Comment by championswimmer** [comment]
Yeah you must sign with same key as the one you uploaded earlier.

**Comment by mananwason** [comment]
See my latest commit and use the keystore.jks file from that while signing apk

**Comment by batraabhishek** [comment]
@mananwason It is not recommended to check keystore file in public repo. https://commonsware.com/blog/2013/01/28/what-not-to-put-in-your-repo.html

**Comment by mariobehling** [comment]
What is the best way to handle this? We want different people to be able to make a release.

**Comment by mananwason** [comment]
@batraabhishek What do you suggest we should do?

**Comment by batraabhishek** [comment]
Email should work. You can email all the contributors. Also for API key, we can maintain 2 sets of key. One for Development and other for Debug. Development API key will be checked in into repo and production API key will be available only with people who have right to make and publish app. Person who makes a release will need to change the API key to production API key. In this way we can continue our development easily, and will have to change key only at the time of release. 

In case some one use the API key, (use without permission or exceeds the quota), we can anytime change the development key, and our released app will continue to work, as they are using production key (which is not public).

**Comment by batraabhishek** [comment]
It is also possible to use a custom debug keystore. This can be used for development API keys that requires SHA1 fingerprint.

**Comment by championswimmer** [comment]
A debug keystore is already checked into the repo by me, and debug apks are
set up to be signed by that.

Release keys, as Abhishek says, should be best shared over Google Drive /
Email attachment. And only with select set of people.

**Comment by mananwason** [comment]
I'll share the release key with the team on drive. Please give me the Email adresses.
