### ISSUE TITLE
Mapping rp15 API to App models

### ISSUE THREAD

**Issue by batraabhishek** [fossasia/rp15#2]
We have the following fields under Speaker
* Name
* Information
* LinkedIn Url
* Twitter Url
* Profile Pic Url

Under Event
* Title
* Sub Title
* Keynote List
* Date
* Time
* Abstract Text
* Description
* Venue
* Track
* Moderator

We need to map these fields from the API

**Comment by championswimmer** [comment]
Just to be handy, the API endpoint is : http://data.re-publica.de/data/
