### ISSUE TITLE
Data not visible in any fragment 

### ISSUE THREAD

**Issue by mananwason** [fossasia/rp15#5]
Data is not visible in any fragment even though it's being saved to the database as I can see in the log, Most probably there is some error in the retrieval process.

**Comment by rafalkowalski** [comment]
Could you check this? I made a fix

**Comment by mananwason** [comment]
@rafalkowalski Doesn't work on my phone. Could you post screens?

**Comment by mananwason** [comment]
@rafalkowalski I see that you removed the arraylist queries which has all the generated queries for the database. Can you explain why did you do it?

**Comment by rafalkowalski** [comment]
Because in file JsonToDatabase we had two variables with the same name("queries"). First was initializing in constructor second in "on response". Besides, we have private attribute queries.

**Comment by mananwason** [comment]
Yes that is true but I don't think it changes anything as all the creations are done before adding queries to the arraylist queries. Anyway it isn't working. Let's try to find any other bug.

**Comment by mananwason** [comment]
@mariobehling @rafalkowalski has fixed this in his latest commit. Should I upload the apk?

**Comment by mariobehling** [comment]
@mananwason If it is working, please upload. So, we can test.

**Comment by mananwason** [comment]
Sure I'll just upload. It'll still be in the beta version only right?

**Comment by mariobehling** [comment]
Yes, until we have tested.

**Comment by mananwason** [comment]
Sure. Should we upload the OTS companion as well, because it's also working now

**Comment by mariobehling** [comment]
Yes, please do. All in beta.

**Comment by mananwason** [comment]
Definitely

**Comment by championswimmer** [comment]
Fyi, On OTS companion, making a tagged commit will generate an apk on
github releases,

**Comment by mananwason** [comment]
@championswimmer So How can I do so ? Will doing so check the app for bugs using travis ?

**Comment by leto** [comment]
@mananwason every commit to the repository will trigger Travis CI to run the configured test suites, unless it is configured to only happen on certain branches/etc

**Comment by mananwason** [comment]
@leto Thanks for the explanation. It would be nice to know that does Travis generate apk by itself or do we have to follow a procedure.

**Comment by championswimmer** [comment]
Everytime you push a commit, travis will build it and test it. If you wish
to skip travis running (for eg just changing README, you can enter "[skip
ci]" without quotes anywhere in your commit message.

Also, if you tag your commit, and push the tag, a corresponding release is
generated with the compiled debug apk.

*make some changes*
git add <files>
git commit -sm "commit message"
git tag "1.1.1"; #NOTE: any tag version name you want to give, not
necessarily semantic version
git push origin --tags #NOTE: remember to push tags before pushing branch
git push origin <the branch you are working on>

=======================================
  Arnav Gupta (championswimmer)
  LinkedIn <http://in.linkedin.com/in/arnavgupta/> | Web
<http://championswimmer.in> | Blog <http://blog.championswimmer.in> |
Twitter <http://twitter.com/championswimmer> | Facebook
<http://facebook.com/championswimmer> | Github
<http://github.com/championswimmer>

**Comment by mananwason** [comment]
Thanks @championswimmer

**Comment by leto** [comment]
@mananwason you can tell Travis to execute any commands you want (including making an APK). It gives you root access to the virtual machine that runs your build/tests/etc

**Comment by leto** [comment]
Can somebody tell me which .travis.yml file we are talking about? I can show people how to use Travis to run your own scripts

**Comment by championswimmer** [comment]
Sure, here
https://github.com/fossasia/ots15-companion/blob/master/.travis.yml
