### ISSUE TITLE
What is this repository?

### ISSUE THREAD

**Issue by leto** [fossasia/rp15#6]
It has no description and no name in the README. What is this thing?

**Comment by mananwason** [comment]
@leto It is the companion app for Re:publica event.

**Comment by leto** [comment]
@mananwason please add some useful information to the README as an exercise in documentation :smile:

**Comment by mananwason** [comment]
@leto sure :smile:

**Comment by rafalkowalski** [comment]
@leto I added few information to README file. Do we need something more?

**Comment by mananwason** [comment]
@rafalkowalski I think this is good. If it's okay @leto, we can close this issue
