### ISSUE TITLE
Data needed from sponsor

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/rp15#7]
Where can I get information about sponsors list? @mariobehling @mananwason

**Comment by mananwason** [comment]
@rafalkowalski There is no sponsors list as such. We just have some sample data on a spreadsheet, which we can use.

**Comment by rafalkowalski** [comment]
Could you give me a link to spreadseet?

**Comment by mananwason** [comment]
Your email address?

**Comment by rafalkowalski** [comment]
rafal.arte@gmail.com

**Comment by mananwason** [comment]
Shared
